using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace Telemedicine.API.Services
{
    public class PdfService
    {
        public byte[] GenerateConsultationSummary(string doctorName, string patientName, DateTime date, string recommendation)
        {
            return Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Size(PageSizes.A4);
                    page.Margin(2, Unit.Centimetre);
                    page.PageColor(Colors.White);
                    page.DefaultTextStyle(x => x.FontSize(11).FontFamily("Arial"));

                    page.Header()
                        .Text("Telemedicine Consultation Summary")
                        .SemiBold().FontSize(20).FontColor(Colors.Blue.Medium);

                    page.Content()
                        .PaddingVertical(1, Unit.Centimetre)
                        .Column(x =>
                        {
                            x.Spacing(20);

                            x.Item().Row(row =>
                            {
                                row.RelativeItem().Column(c =>
                                {
                                    c.Item().Text("Doctor:").SemiBold();
                                    c.Item().Text(doctorName);
                                });

                                row.RelativeItem().Column(c =>
                                {
                                    c.Item().Text("Patient:").SemiBold();
                                    c.Item().Text(patientName);
                                });

                                row.RelativeItem().Column(c =>
                                {
                                    c.Item().Text("Date:").SemiBold();
                                    c.Item().Text(date.ToString("f"));
                                });
                            });

                            x.Item().LineHorizontal(1).LineColor(Colors.Grey.Medium);

                            x.Item().Text("Recommendation / Summary:").FontSize(14).SemiBold();
                            
                            x.Item().Border(1).BorderColor(Colors.Grey.Medium).Padding(10).Text(recommendation ?? "No specific recommendation.");

                            x.Item().Text("This document is automatically generated by the Telemedicine Platform.").FontSize(9).FontColor(Colors.Grey.Medium);
                        });

                    page.Footer()
                        .AlignCenter()
                        .Text(x =>
                        {
                            x.Span("Page ");
                            x.CurrentPageNumber();
                        });
                });
            })
            .GeneratePdf();
        }
    }
}
